length=input('enter the length of the rectangle')
length=float(length)
width=input('enter the width of the rectangle')
width=float(width)
perimeter=(length+length+width+width)
perimeter=float(perimeter)
price=input('enter the price per metre of fencing')
price=float(price)
cost=(price*perimeter)
print('the cost of fencing is:',cost)
